openapi: "3.0.0"

info:
  title: API des classes #ca sera utiliser pour les endPoint @RequestMapping("${openapi.aPIDeTest.base-path:/service/api}")
  version: "1.0"
  description: Microservice des classes de openAPI

servers:
  - url: http://localhost:8080/classes/api

tags:
  - name: Classes
    description: Classes specific data.
  - name: Filieres
    description: Filieres specific data.
  - name: Cycles
    description: Cycles specific data.

paths:

  ##############
  ## API Classes ##
  ##############

  /classes:
    $ref: '../components/api/classes.yml#/paths/~1classes'

  /classes/{idClasse}:
    $ref: '../components/api/classes.yml#/paths/~1classes-reference'
