/**
 * API des classes
 * Microservice des classes de openAPI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClasseDTO } from './classeDTO';


export interface ClassesResultListDTO { 
    /**
     * The List of the ClasseDTO.
     */
    classeList?: Array<ClasseDTO>;
}

